name       : perl-timedate
version    : 2.30
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GB/GBARR/TimeDate-2.30.tar.gz : 75bd254871cb5853a6aa0403ac0be270cdd75c9d1b6639f18ecba63c15298e86
license    : Artistic-1.0-Perl
summary    : Perl Time & Date Functions
description: |
    Perl Time & Date Functions
patterns   :
    - /usr/share/man
setup      : |
    perl Makefile.PL PREFIX=/usr INSTALLDIRS=vendor DESTDIR=%installroot%
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/lib/perl5/5.20.1
