name       : perl-timedate
version    : '2.33'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/TimeDate-2.33.tar.gz : c0b69c4b039de6f501b0d9f13ec58c86b040c1f7e9b27ef249651c143d605eb2
homepage   : https://metacpan.org/dist/TimeDate
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl Time & Date Functions
description: |
    Time & Date parsing and formatting Perl library
patterns   :
    - /usr/share/man
rundeps    :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
