name       : perl-timedate
version    : 2.3
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GB/GBARR/TimeDate-2.30.tar.gz : 75bd254871cb5853a6aa0403ac0be270cdd75c9d1b6639f18ecba63c15298e86
license    : Artistic-1.0-Perl
summary    : Perl Time & Date Functions
component  : programming.perl
description: |
    Perl Time & Date Functions
patterns   :
    - /usr/share/man
rundeps    :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
